# Generated by Django 4.2.3 on 2025-03-02 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('specialties', models.ManyToManyField(related_name='teams', to='gaharwb.specialty')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DONE', 'خاتمه یافته'), ('IN_PROGRESS', 'در حال انجام'), ('Available', 'در دسترس')], default='Available', max_length=11)),
                ('rfp', models.FileField(blank=True, null=True, upload_to='media/rfps/')),
                ('functor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='gaharwb.team')),
                ('requested_teams', models.ManyToManyField(related_name='requested_projects', to='gaharwb.team')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ('title', 'status', 'publish_date'),
            },
        ),
        migrations.CreateModel(
            name='Request_for_Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 شروع شود.', regex='^98\\d{10}$')])),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/requests/')),
                ('specialties', models.ManyToManyField(to='gaharwb.specialty')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست های همکاری',
                'unique_together': {('fname', 'lname')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40, null=True)),
                ('lname', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 شروع شود.', regex='^98\\d{10}$')])),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید شامل 10 رقم باشد.', regex='^\\d{10}$')])),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/resumes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('role', models.CharField(choices=[('leader', 'سرپرست تیم'), ('advisor', 'مشاور تیم'), ('member', 'عضو تیم')], default='member', max_length=7)),
                ('specialties', models.ManyToManyField(to='gaharwb.specialty')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gaharwb.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
                'ordering': ('fname', 'lname', 'role', 'team'),
                'unique_together': {('fname', 'lname')},
            },
        ),
    ]
