# Generated by Django 4.2.3 on 2025-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0003_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requested_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_projects', to='gaharwb.team'),
        ),
    ]
