# Generated by Django 4.2.3 on 2025-03-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0004_alter_project_requested_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('fname', 'lname', 'role', 'team'), 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
    ]
