# Generated by Django 4.2.3 on 2025-03-07 07:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaharwb', '0005_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(max_length=40, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lname',
            field=models.CharField(max_length=40, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='member',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید شامل 10 رقم باشد.', regex='^\\d{10}$')], verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 شروع شود.', regex='^(\\+98|0)9\\d{9}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/resumes/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('leader', 'سرپرست تیم'), ('advisor', 'مشاور تیم'), ('member', 'عضو تیم')], default='member', max_length=7, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialties',
            field=models.ManyToManyField(to='gaharwb.specialty', verbose_name='تخصص ها'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gaharwb.team', verbose_name='نام تیم'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اکانت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='functor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='gaharwb.team', verbose_name='نام تیم'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requested_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_projects', to='gaharwb.team', verbose_name='تیم های متقاضی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rfp',
            field=models.FileField(blank=True, null=True, upload_to='media/rfps/', verbose_name='فایل نیاز تفضیلی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DONE', 'خاتمه یافته'), ('IN_PROGRESS', 'در حال انجام'), ('Available', 'در دسترس')], default='Available', max_length=11, verbose_name='وضعیت پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان پروژه'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 شروع شود.', regex='^98\\d{10}$')], verbose_name='اکانت'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/requests/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='specialties',
            field=models.ManyToManyField(to='gaharwb.specialty', verbose_name='تخصص ها'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان تخصص'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='نام تیم'),
        ),
        migrations.AlterField(
            model_name='team',
            name='specialties',
            field=models.ManyToManyField(related_name='teams', to='gaharwb.specialty', verbose_name='تخصص ها'),
        ),
    ]
