# Generated by Django 4.2.3 on 2025-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0006_alter_member_email_alter_member_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_for_collaboration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requested_teams',
            field=models.ManyToManyField(blank=True, related_name='requested_projects', to='gaharwb.team', verbose_name='تیم های متقاضی'),
        ),
    ]
