# Generated by Django 4.2.3 on 2025-03-08 09:20

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0007_request_for_collaboration_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 شروع شود.', regex='^(\\+98|0)9\\d{9}$')], verbose_name='شماره تماس'),
        ),
    ]
