# Generated by Django 4.2.3 on 2025-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0008_alter_request_for_collaboration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
