# Generated by Django 4.2.3 on 2025-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0009_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
