# Generated by Django 4.2.3 on 2025-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0010_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('expert', 'حرفه ای')], default='beginner', max_length=12, verbose_name='سطح تیم'),
        ),
    ]
