# Generated by Django 4.2.3 on 2025-04-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0011_team_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requested_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_projects', to='gaharwb.team', verbose_name='تیم های متقاضی'),
        ),
    ]
