# Generated by Django 4.2.3 on 2025-04-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0012_alter_project_requested_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
