# Generated by Django 4.2.3 on 2025-04-26 10:22

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0013_alter_request_for_collaboration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_for_collaboration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request_for_collaboration',
            name='otp_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='request_for_collaboration',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقمی باشد و با 98 یا 0 شروع شود.', regex='^(\\+98|0)9\\d{9}$')], verbose_name='شماره تماس'),
        ),
    ]
