# Generated by Django 5.2.1 on 2025-05-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0014_request_for_collaboration_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
