# Generated by Django 4.2.3 on 2025-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0019_alter_request_for_collaboration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='email',
            field=models.EmailField(default='exemple@gmail.com', max_length=254, verbose_name='ایمیل'),
        ),
    ]
