# Generated by Django 4.2.3 on 2025-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0020_alter_request_for_collaboration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_collaboration',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
