# Generated by Django 4.2.3 on 2025-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0021_alter_request_for_collaboration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_for_collaboration',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request_for_collaboration',
            name='otp_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
