# Generated by Django 4.2.3 on 2025-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharwb', '0022_request_for_collaboration_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='../static/images/teams.png', upload_to='media/images/teams/', verbose_name='تصویر'),
        ),
    ]
